# # # # # # # # # # # # #
#     Fat-Tea-House     #
#   Melody of Oblivion  #
# # # # # # # # # # # # #

# Basic
name:               "Melody of Oblivion"
suffix:             "Garden"
sub:                "Level Up!"
author:             "monSteRhhe"
url:                "https://melody-of-oblivion.github.io"

copyright:
  year:             2020
  name:             Fat Tea House

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           13
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - href:           /
    name:           "Home"
  - href:           /about/
    name:           "About"
  - href:           /applist/
    name:           "Applist"

# Sass
sass:
  sass_dir:         /assets/css
  style:            :compressed

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Post
create_date:        "创建时间"
edit_date:          "最后编辑"