# # # # # # # # # # # # #
#     Fat-Tea-House     #
#   Melody of Oblivion  #
# # # # # # # # # # # # #

# Basic
name:               "Melody of Oblivion"
suffix:             "Garden"
author:             "monSteRhhe"
url:                "https://melody-of-oblivion.github.io"
rssfeed:             true

copyright:
  enable:           true
  year:             2023
  name:             Fat Tea House

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           13
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - href:           /
    name:           "Home"
  - href:           /about/
    name:           "About"
  - href:           /applist/
    name:           "Applist"

# Sass
sass:
  sass_dir:         /assets/css
  style:            :compressed

# Scopes
defaults:
  - scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Post Detail
create_date:        "发表时间"
edit_date:          "最后编辑"

# Socail Links
mapping_icons:
  enable:           true

# Mapping Social Icons
social_icons:
  # Icons & Links
  ## FontAwesome icons' name refers to https://fontawesome.dashgame.com/ 
  ### isfa - true/false
  ### faicon - FontAwesome icons' name
  Github:
    enable:         true
    isfa:           false
    link:           "https://github.com/monSteRhhe"

  Mail:
    enable:         true
    isfa:           false
    link:           "mochimito@outlook.com"

  Weibo:
    enable:         false
    isfa:           true
    faicon:         "fa-weibo"
    link:           ""
    description:    "My Weibo"

  Twitter:
    enable:         false
    isfa:           true
    faicon:         "fa-twitter"
    link:           ""
    description:    "My Twitter"

# Sub description
## a short sentense, displayed on the right side of the main page.
sub:                true
subwords:           "To explore the world."
